(((min-height . 12)
  (min-width . 20)
  (min-height-ignore . 6)
  (min-width-ignore . 10)
  (min-height-safe . 3)
  (min-width-safe . 4)
  (min-pixel-height . 156)
  (min-pixel-width . 140)
  (min-pixel-height-ignore . 78)
  (min-pixel-width-ignore . 70)
  (min-pixel-height-safe . 39)
  (min-pixel-width-safe . 28))
 vc
 (pixel-width . 1912)
 (pixel-height . 1031)
 (total-width . 273)
 (total-height . 79)
 (normal-height . 1.0)
 (normal-width . 1.0)
 (combination-limit)
 (hc (pixel-width . 1912)
     (pixel-height . 247)
     (total-width . 273)
     (total-height . 19)
     (normal-height . 0.23957322987390883)
     (normal-width . 1.0)
     (combination-limit)
     (leaf (pixel-width . 953)
           (pixel-height . 247)
           (total-width . 136)
           (total-height . 19)
           (normal-height . 1.0)
           (normal-width . 0.5)
           (parameters (gdb-buffer-type . command))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0)
                   (fringes 8 8 nil nil)
                   (margins nil)
                   (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0)
                   (dedicated)
                   (point . 1)
                   (start . 1)))
     (leaf (last . t)
           (pixel-width . 959)
           (pixel-height . 247)
           (total-width . 137)
           (total-height . 19)
           (normal-height . 1.0)
           (normal-width . 0.5)
           (parameters (gdb-buffer-type . gdb-locals-values-buffer))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0)
                   (fringes 8 8 nil nil)
                   (margins nil)
                   (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0)
                   (dedicated . t)
                   (point . 1)
                   (start . 1))))
 (hc (pixel-width . 1912)
     (pixel-height . 520)
     (total-width . 273)
     (total-height . 40)
     (normal-height . 0.504364694471387)
     (normal-width . 1.0)
     (combination-limit)
     (leaf (pixel-width . 953)
           (pixel-height . 520)
           (total-width . 136)
           (total-height . 40)
           (normal-height . 1.0)
           (normal-width . 0.5)
           (parameters (gdb-buffer-type . source))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0)
                   (fringes 8 8 nil nil)
                   (margins nil)
                   (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0)
                   (dedicated)
                   (point . 1)
                   (start . 1)))
     (leaf (last . t)
           (pixel-width . 959)
           (pixel-height . 520)
           (total-width . 137)
           (total-height . 40)
           (normal-height . 1.0)
           (normal-width . 0.5)
           (parameters (gdb-buffer-type . gdb-inferior-io))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0)
                   (fringes 8 8 nil nil)
                   (margins nil)
                   (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0)
                   (dedicated . t)
                   (point . 1)
                   (start . 1))))
 (hc (last . t)
     (pixel-width . 1912)
     (pixel-height . 264)
     (total-width . 273)
     (total-height . 20)
     (normal-height . 0.2560620756547042)
     (normal-width . 1.0)
     (combination-limit)
     (leaf (pixel-width . 953)
           (pixel-height . 264)
           (total-width . 136)
           (total-height . 20)
           (normal-height . 1.0)
           (normal-width . 0.5)
           (parameters (gdb-buffer-type . gdb-stack-buffer))
           (buffer " *gdb-placeholder*" (selected)
                   (hscroll . 0)
                   (fringes 8 8 nil nil)
                   (margins nil)
                   (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0)
                   (dedicated . t)
                   (point . 1)
                   (start . 1)))
     (leaf (last . t)
           (pixel-width . 959)
           (pixel-height . 264)
           (total-width . 137)
           (total-height . 20)
           (normal-height . 1.0)
           (normal-width . 0.5)
           (parameters (gdb-buffer-type . gdb-breakpoints-buffer))
           (buffer " *gdb-placeholder*" (selected . t)
                   (hscroll . 0)
                   (fringes 8 8 nil nil)
                   (margins nil)
                   (scroll-bars nil 0 t nil 0 t nil)
                   (vscroll . 0)
                   (dedicated . t)
                   (point . 1)
                   (start . 1)))))
